### ISSUE TITLE
[kwallet]: disable kwallet / prevent from pop up

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#163]
two popups come up and you cannot close the second one...

**Comment by mck182** [comment]
I have working pam-kwallet5 (not yet upstream), maybe that could be deployed on the phone?

**Comment by star-buck** [comment]
mck182: i suggest to not bring annyoing kwallet on the phone for akademy, purely to avoid negative connotations whenever possible...

**Comment by star-buck** [comment]
@Riddell: another conflict, so please remove signon-kwallet-extension, quoting:

(4:00:23 PM) mck182___: however it needs signon-kwallet-extension removed first, but it's a hard dependency of some other things so the packaging needs to be adjusted first

**Comment by apachelogger** [comment]
the important bit is -> "[..] but it's a hard dependency of some other things so the packaging needs to be adjusted first"

**Comment by star-buck** [comment]
kwallet still pops up

**Comment by star-buck** [comment]
neon IMG1: popup still prevents connecting to WLAN from interface, can we disable kwallet for now, so kded5 doesnt request i...

**Comment by bhush9** [comment]
As a workaround,

we could disable kwallet5 with this in .config/kwalletrc

```
[Wallet]
Close When Idle=false
Close on Screensaver=false
Enabled=false
Idle Timeout=10
Launch Manager=false
Leave Manager Open=false
Leave Open=true
Prompt on Open=false
Use One Wallet=true
```

**Comment by bhush9** [comment]
I will give it try locally to see if it works.

**Comment by apachelogger** [comment]
fwiw at this point all that is needed is
- have pam-kwallet on the CI
- have simplelogin's pam actually load the module
- ship pam-kwallet5 in the image

**Comment by mck182** [comment]
I've tried, it won't work.

kwallet-pam complains about not having the password. Although maybe it requires a pre-set kwallet? Which I don't have because the dialog does not fit the touchscreen...

simplelogin: pam_kwallet5(sddm-autologin:auth): (null): pam_sm_authenticate
simplelogin: pam_kwallet5(sddm-autologin:auth): pam_kwallet5: Couldn't get password (it is empty)
simplelogin: pam_kwallet5(sddm-autologin:auth): pam_kwallet5: Prompt for password failed Unknown PAM error
simplelogin: pam_kwallet5(sddm-autologin:setcred): pam_kwallet5: pam_sm_setcred
simplelogin: pam_kwallet5(sddm-autologin:session): pam_kwallet5: pam_sm_open_session
simplelogin: pam_kwallet5(sddm-autologin:session): pam_kwallet5: open_session called without kwallet5_key

**Comment by apachelogger** [comment]
Ah uh yeah, that actually makes sense. Kind of.

The way the module works (I think) is it asks PAM for the user password it was provided (from the login manager) and then salts that and throws it at kwalletd to use as password for the wallet.
BUT, on autologin there is no password involved so the module refuses to create a wallet on account of it being a passwordless wallet (unintentionally mind you).

So we could kill kwallet which likely will make apps angry (e.g. I recall plasma-nm refusing to store passwords for user-only connections without kwallet). Or we give pam_kwallet an override to allow passwordless wallets. Or we fix this properly and create a firststartwizard and unlocking tech so that we always auth against PAM with something. I mean, right now the phone is as insecure as it can be anyway.

**Comment by mck182** [comment]
> Or we fix this properly and create a firststartwizard and unlocking tech so that we always auth against PAM with something

The phone could boot to a lockscreen which is a real lockscreen with passwords/pin/code, unlocking the screen for the first time would unlock the wallet. If user sets no password/pin/code, the wallet would be passwordless.

This would require the lockscreen setting to sync the password to the wallet though.

**Comment by star-buck** [comment]
neon-img v9:
still comes up, leaving password fields empty brings up confirmation window (weak passwords) which is too long to be able to confirm

**Comment by mck182** [comment]
Yeah, for the approach mentioned above we need:
 - https://git.reviewboard.kde.org/r/125641/
 - working lockscreen on the phone (I understand @bhush9 got something working)
 - preinstalled kwallet file

In the meantime, I think we should just ship a premade kwallet file with empty password. @jriddell can you look into that? You said you do something like that in Kubuntu.

**Comment by star-buck** [comment]
Please lets do that for kwallet5 and kwallet4 for now. Riddell: Post both
solutions here, so we know how we did it just in case.

**Comment by bhush9** [comment]
Small update: kwin_wayland got --lockscreen option, which will start lockscreen when used. It is not really secure at moment but enough for this purpose.

**Comment by bhush9** [comment]
http://commits.kde.org/kwin/bacfd876fecf2df72ba38d651f637a720e108581

It will need packaging kscreenlocker repo and update in kwin.

**Comment by bhush9** [comment]
http://commits.kde.org/scratch/davidedmundson/simplelogin/89328a01cbf67d917e2c7364289ad9c3fe0c501b

As lockscreen for mobile was fixed in kwin, I've now enabled the lockscreen on boot for phone.. @mck182 : now what needs to be done to do unlock-screen-to-unlock-wallet for mobile?

**Comment by star-buck** [comment]
seems with lockscreen, kwallet no longer pops up as of img14...
