### ISSUE TITLE
[peruse]: doesnt start

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-img#232]

**Comment by star-buck** [comment]
konsole throws error message: 
Mobilemain.qml:97 Type Bookshelf unavailable

**Comment by leinir** [comment]
There should be more errors than that, unless Bookshelf isn't packaged (which would be strange, as it's just a qml file installed alongside MobileMain.qml). I'm using multirom, so i can't check this error right now, but i shall test it when Bhushan pushes the next release. If you can get me the full output, though, i should be able to diagnose it more easily :)

**Comment by bhush9** [comment]
I've really messed up multirom setups by enabling lockscreen by default.. I will be able to redo next image tomorrow morning. :-(

**Comment by star-buck** [comment]
@bhush9 : if certain parts of the prototype influence specifically multirom, dont care for them. We all have a Nexus 5 fully to be used with PM only if necessary at this point. 

@leinir :
PM img not working on multirom is NOT an excuse to not test latest img.

**Comment by bhush9** [comment]
@star-buck Yes, but well.. I personally use multirom based setup because it is more convenient to have two different images installed, one stable and one devel-proposed for testing purpose. Also lockscreen starting without setting password is bug that we will have to fix on lockscreen stack.

**Comment by star-buck** [comment]
@bhush9 : yes, but we dont have to do that now. 1234 for non multirom is fine. also "stable" rom is as good or bad as non-stable at this point, unless devel-proposed is getting so much worse with each progression that its almost unusable... again, not testing devel-proposed because of multirom is NO excuse with everyone within blue systems having a nexus 5 exactly for testing devel-proposed.

**Comment by star-buck** [comment]
@leinir : please test peruse on img14 yourself and see whats wrong.

**Comment by leinir** [comment]
Right, turns out it was caused by a change in the mobile components. Fixed in 877024ee2335c5828bbf83b5a2224f0a1384368f, should be sorted next time the peruse package is updated - @bhush9 over to you :)

@star-buck Minor comment on the error output, the relevant log entry was the last error, which said that Categoryshelf.qml:33 Cannot assign to non-existent property "flickable" (just to make things easier another time an error like that happens, though hopefully the adjustment to my workflow to include updating my local mobile components more often should avoid this particular issue happening)

**Comment by bhush9** [comment]
packaged. will be in next image..

**Comment by star-buck** [comment]
it seems to start after upgrading all packages.
So what file format does it pick up and where do I have to put the files for Peruse to find them?

**Comment by star-buck** [comment]
opening new ticket
